### ISSUE TITLE
All Bots Rush To Your Location

### ISSUE THREAD

**Issue by BraveStarG** [Solarint/SAIN#136]
This has been happening since the last 3 or 4 updates. The moment you getting into a fight with any bot or you make any noise whatsoever every bot within range (20, 40 or even 60 meters away) just funnels quietly into the area your in straight to where you are regardless if you're in a room with closed doors, away from the noise you made or where the bot was killed, no matter the floor. They just come straight at you in groups and even open doors without making any noise. Scavs, player scavs, PMC, it doesn't matter, they all come straight to you. Even if you move. I used the radar mod to see them and I can see them come straight to me. The more you kill the more of them keep coming. I never had so many bots come straight to my location no matter how much noise I made. I have video footage to show it if necessary.

**Comment by ThanosWasntWrong** [comment]
Exactly, i brought this up on the comment section and the author of the mod closed the comments section(lol).

The last proper SAIN version was 2.2.1-Hotfix. After that the mod has been taking a U-turn for the worst. There's 3 types of bots now: 1. the Scavs that stand around or walk in back to back straight lines and are asking to get shot. 2. The PMC that literally camps rooms in either crouch/prone stances waiting for you to peak. And 3. the 1 magical PMC/BOSS that knows exactly where you are and sprints towards you and magically 1 taps your head every time you're in sight.

In SAIN 2,2.1-Hotfix, none of these basic bot behaviours existed. Bots pushed/retreated, temporarily camped/repositioned, pmcs who had grenades actually used them and finally the last 2 points, bots didn't magically know where you were nor did they magically 1 tap you at every engagement.  I had a firefight in 2.2.1 last night where a pmc with a m4 hailed me with bullets and i had half my body out of a small cover, i got hit a few times, i didn't get 1 tapped. It was a proper firefight. None of this typical aimbot-nobulletspread bullshit.

Like i said, guy turned off comments on sp-tarkovhub after people started commenting on how odd the results on the new patches were. So there's some legitimate doubt that this will get fixed.

**Comment by Solarint** [comment]
Wow you really have no idea what you are talking about.

**Comment by Solarint** [comment]
Bots have a longer memory. Both you, and the bots now - can easily hear footsteps from 60 meters away (footsteps are audible in tarkov up to almost 70 meters away if you are wearing headphones), if they hear you walk into a room, they will update their known position of you properly.

**Comment by Solarint** [comment]
The reason bots were never investigating properly in old versions was due to search having serious bugs, causing bots to get stuck  in a loop of repeaking the same corner over and over again, until they eventually "forget" about their enemy and return to their peaceful logic. Fixing that is what causes them to be much more intent on chasing you. Basically, they were always like this, but a bug caused them to fail to execute.

**Comment by BraveStarG** [comment]
So I should always expect every bot within range to just come straight to my spot regardless if I move and making any sound will draw them right to me, even if I don't make any noise and stand still behind cover? I'll be honest. I always wondered why bots didn't always come to where the fighting was. Both PMCs and scavs. But I never expect such pinpoint location finding. I get the point of it being this way but even in a Live game PMC didn't just funnel in one behind the other just to kill you, followed by another PMC team within seconds and often scavs as well. But I'll mess around with the settings to see if I can get them to not all just horde straight at me no matter where I am relative to them. Any advice of what settings I can mess with for that?

**Comment by Paragonid** [comment]
### Summary:
1. Bots don't seem to have uncertainty about the player position, especially noticeable during looting/healing (maybe it's too loud for them). It's like they know your exact room in a building even though they heard you from 60 meters.
2. Bots are not considerable of dangerous situations like CQB in cottages with many rooms and corners, they aren't afraid and not delayed rushing in through them.
3. My settings are "Harder PMC" on latest SAIN and I have SWAG + DONUTS default settings of dynamic bot spawns. Possibly, the problem is that the bots are too plentiful and there are too many of them who have reckless engagement as their highest priority.


### Details: 
Examples which make me feel bad about current bot behavior (I play with default settings of SWAG + DONUTS, so bots are plentiful through the raid):
Shoreline, the cottage near ambulance, I went in to loot a safe, some bots were walking around and I shoot them through the window, I got hit and stayed to heal. In next 5 minutes, I killed 6 PMCs rushing inside to kill me in 3 different waves. They know exactly which room I sit in, they don't care to look around and not careful of any other corner or room, they don't have any uncertainty even if I didn't move for some time.
Shoreline, same situation for a room in between stairs and a air pass, 2 floor east wing, I find a dead body, slowly loot, 2 PMCs push my position, then 3 more in separate waves.
This happens often and pretty much everywhere, if I spend a bit longer looting a body in any position without making loud sounds for 2-3 minutes, I still can be sure there will be many clearing groups coming exactly at my position (often without headphones)

Sidenote: bots are very stupid trying to attack behind a door. They know exactly the 2 square meters room I'm in, and they still come up to the middle of the closed door to open it, often pushing weapons through it.

**Comment by BraveStarG** [comment]
> ### Summary:
> 1. Bots don't seem to have uncertainty about the player position, especially noticeable during looting/healing (maybe it's too loud for them). It's like they know your exact room in a building even though they heard you from 60 meters.
> 2. Bots are not considerable of dangerous situations like CQB in cottages with many rooms and corners, they aren't afraid and not delayed rushing in through them.
> 3. My settings are "Harder PMC" on latest SAIN and I have SWAG + DONUTS default settings of dynamic bot spawns. Possibly, the problem is that the bots are too plentiful and there are too many of them who have reckless engagement as their highest priority.
> 
> ### Details:
> Examples which make me feel bad about current bot behavior (I play with default settings of SWAG + DONUTS, so bots are plentiful through the raid): Shoreline, the cottage near ambulance, I went in to loot a safe, some bots were walking around and I shoot them through the window, I got hit and stayed to heal. In next 5 minutes, I killed 6 PMCs rushing inside to kill me in 3 different waves. They know exactly which room I sit in, they don't care to look around and not careful of any other corner or room, they don't have any uncertainty even if I didn't move for some time. Shoreline, same situation for a room in between stairs and a air pass, 2 floor east wing, I find a dead body, slowly loot, 2 PMCs push my position, then 3 more in separate waves. This happens often and pretty much everywhere, if I spend a bit longer looting a body in any position without making loud sounds for 2-3 minutes, I still can be sure there will be many clearing groups coming exactly at my position (often without headphones)
> 
> Sidenote: bots are very stupid trying to attack behind a door. They know exactly the 2 square meters room I'm in, and they still come up to the middle of the closed door to open it, often pushing weapons through it.

Basically this. Thank you.

**Comment by malfboi** [comment]
How much have you configured the SAIN settings and spawn settings with Donuts? In my experience there is a lot of behaviour to be modified from the default settings, I found turning down hearing range and aggressiveness works pretty well. 

If you have looting bots massively decrease the range of corpse looting and add the line of sight check otherwise any PMC within 50m of your gun fight (even if its been quiet for a while) is going to run straight to the corpses.

With Donuts you can set the PMCs to not spawn within a certain range of you, if you put this well over the range of hearing they should not spawn and rush you.

Look at the Personality settings in SAIN and turn off chasing gunshots.

Also make difficulty levels with your own settings, go to `SAIN -> Bot Settings -> PMCs -> Select Usec & Bear -> Select all difficulties` . Now you can customise each level to throw grenades, be more innacurate, less aggressive, etc. I would really recommend going and looking at each setting. Before going into a raid in your Donuts menu `Donuts PMC Spawn Difficulty` is where you select your relative difficulty level for the PMCs to spawn with. 

With Donuts I created a Raid Preset copied from live-like but with the bot spawns capped at a certain level, e.g: `live-like-6, live-like-8, live-like-10`, before a raid I select live-like-8 and with `Bot Hard Cap Option: Enabled` it means in my raid only 6 PMCs and 6 Scavs will be alive at one time. Use `Global Minimum Spawn Distance From Player` to make them not feel like they are respawning on top of you. Use `Cool Down Timer` to slow down the spawn intervals. Finally use `PMC Spawn Hard Stop` and `PMC Spawn Hard Stop: Time Left in Raid` to stop constant spawns through the raid, I change this dependent on map and the feel I am going for. 

I use these settings to create nice solo raids on Woods to chaotic 5 man Labs.

**Comment by BraveStarG** [comment]
I think I see what could be the real issues. Maybe because SAIN has been updated in such a way that it works more like it's supposed to, closer to what Live is like with real players that a combination of better, more life like reacting bots, better looting bots, better questing bots and Donuts/SWAG are simply making the bots a bit too robotic and thus tweaking one mod requires tweaking the rest to avoid creating bots that literally act like bots.

I'll work on tweaking every mod that involves AI to see if I can find a more balanced raid where the bots still come looking for me without just coming like zombies. I'll update on my progress. Thanks for all the details. I understand better what the issues might be. This should really help

**Comment by Paragonid** [comment]
@malfboi @BraveStarG I agree, mod combination might be an actual issue, thanks for the insides

**Comment by Paragonid** [comment]
I tested a bit today, I believe the issue of bots wave chasing the player became worse with one of the resent updates.
I have 4 scavs which shouldn't be effected by other AI mods slowly walking one by one into the room with Saving the Mole disk just because one of them probably heard steps from the park. And of course when I shoot one, the rest follow up.
I don't remember experiencing this before, it feels like their desire to investigate one step and their preciseness in understanding the exact position is too much, and as soon as a shot is fired, all the bots in the range queue up

The looting bots possible AI changes isn't an issue for this one, and I don't see anything else that can effect it.
Sure, I can attempt to configure hearing ranges, but I think this behavior pattern is very robotic in nature

**Comment by malfboi** [comment]
Under `SAIN -> Personalities` Look for `Will Chase Gunshots` . Do make sure you change the `Global -> Hearing`  Footstep and Gunshot range.

**Comment by malfboi** [comment]
I would also recommend installing https://hub.sp-tarkov.com/files/file/1981-dynamic-maps/ and enabling the enemy markers to more easily view AI behaviour, see how they react when you fire a shot or make a step. There is also this mod https://hub.sp-tarkov.com/files/file/279-freecam/ so you can freecam and teleport.

**Comment by muzica9** [comment]
Yes, it is quite annoying, and break the immersive experience. I did some tests. Sitting in labs, in violet or yellow rooms: no shooting, no looting, no healing, no noise. Whole map, pmcs and raiders, one by one or multiple of them, opened the door and came straight to me. looting bots and questing bots mods off.

**Comment by malfboi** [comment]
Try turning down hearing range, turning down aggression and try installing: https://hub.sp-tarkov.com/files/file/1453-that-s-lit-logical-ai-vision/

It is an AI vision overhaul and works well with SAIN

**Comment by muzica9** [comment]
> Try turning down hearing range, turning down aggression and try installing: https://hub.sp-tarkov.com/files/file/1453-that-s-lit-logical-ai-vision/
> 
> It is an AI vision overhaul and works well with SAIN

test was made with THAT'S LIT mod installed and Global -> Hearing Footstep and Gunshot ranges set to 0.5. they still know exactly where you are, beeing dead quiet.

**Comment by Solarint** [comment]
Fixed and overhauled in later versions, especially 3.0.0
