### ISSUE TITLE
Bots are just too hard.

### ISSUE THREAD

**Issue by twistbud** [Solarint/SAIN#81]
So I got a question, its the biggest problem I have with ai combat mods, so the scavs are dumb and fun like usual, but the pmcs? well I only seem to run across pmcs that rush and peek me over and over, no "timmys" or rats it seems, but thats not the biggest problem, my biggest issue is that the ai is just too damn hard. I have it on "easy" and I wouldnt call it easy, idk if its something I have done but most of the time the ai just doesnt miss, ive done tests in raids with godmode on and see ai peek behind a tree with a garbage weapon and nail me from at least 20 ft away and not miss a single shot, so I am wondering if there is something I could do to make the ai a little more forgiving, thank you.

Also just want to say, I love this mod its amazing, thats why I want to balance it out, its the core of my spt mod list, and also, I have all requirements for the mod and went over all compatible issues, including the fix for spt realism.

Posted this from the spt website then deleted it, didnt realize there was this help page. ill send two screenshots of my mods and plugins.
![e8f2395e-96f1-4c8d-96b1-7a58d6456b6e](https://github.com/Solarint/SAIN/assets/142971556/bff40e34-6543-4bbf-9915-9766bf65f81d)
![dd6029ce-3609-41eb-9b7e-4e5a72ffba63](https://github.com/Solarint/SAIN/assets/142971556/3e1a0a54-3e3a-4437-b866-4e0107b84164)

**Comment by twistbud** [comment]
I have all required mods. I am on the latest version of spt 3.6.1, cant send the zip but I am using the default EASY preset.

**Comment by twistbud** [comment]
![e2ba8509-0ee2-4998-ac75-2e756510df24](https://github.com/Solarint/SAIN/assets/142971556/8a4ac883-53b6-4125-9b52-a86fc73ad34f)



my bots settings on realism, also I am using the default easy preset on sain with the only changed setting being the one that removes the bot's ability to snap to your head, I turned that on.

**Comment by Solarint** [comment]
I'm not sure, because when I was making the difficulty presets in SAIN's config menu, the bots were basically useless on easy. You are changing the preset in the f6 menu right?

**Comment by WhoAreYou94** [comment]
Howdy, I know this was a little bit ago but I thought I'd chime in to see if this helps.

I was having the same sort of issues when it came to PMC's and Raiders etc at the higher levels whilst using realism (without the bot difficulty changes (when their bullets are doing the big ouchies across the board). I went in and turned down SAIN the same way you did but thought the issue may be stemming from the individual bots settings as I was still getting one tapped pretty darn quickly (at close range), so I presumed it had something to do with CQB or the like. This lead me to find out something I did not know:

### HERE IS HOW I "FIXED IT"
I always set the game to "As online" because its the default and none of the mods I have used in the past seemed to really do much with it to my knowledge. HOWEVER,  This setting determines the "difficulties" of the bots that spawn. So, if you set the difficulty to "AS ONLINE" it has a chance to spawn bots at any difficulty from the highest to lowest. with the respective difficulties only spawning bots of that difficulty (I.E. Easy will only spawn easy etc). So set this to your preferred difficulty and you can either tweak the bot difficulties for that setting to your liking or run it with the preset options and see how you go, after changing this and turning down the CQB functions I found it to be a lot better for me.
